{ ... }:

# The reviewed secondary deployment shape.  CriomOS remains the owner of
# UserEnvironment realization and activation; this module only composes the
# two user-scoped Home modules that the deployment selects.
#
# runtimeRouteFile intentionally remains unset.  A null route file is the
# fail-closed unknown-only route generated by the relay module.  A witnessed
# Flow-owned route file may be supplied by the OS-side deployment request.
{
  imports = [
    ../core-packages.nix
    ./cf7879-cluster-relay.nix
    ../profiles/min/core-checkup.nix
    ../profiles/min/core-checkup-primary-successor.nix
  ];

  config = {
    criomosHome.clusterRelay.enable = true;
    criomosHome.coreCheckup.enable = true;
  };
}
